### ISSUE TITLE
Firefox and Chrome do not run in app containers

### ISSUE THREAD

**Issue by TahaRostamii** [M2Team/Privexec#42]
Firefox and Chrome can't be started in AppContainer.

![Screenshot (11)](https://github.com/M2Team/Privexec/assets/126977082/fc18c4fa-e16b-4cde-badc-ecafdbdc0fa0)

They are not executed despite the permissions I have given.

**Comment by fcharlie** [comment]
This problem is actually a bit complicated. Not all programs can be started under AppContainer permissions. This may be related to permissions, or it may be related to the dependencies of the program itself.

**Comment by WildByDesign** [comment]
Indeed, multi-process programs are much more complex. Particularly browsers because each process they spawn has a variety of unique sandboxing policies applied to them.

On a positive note, I have been running latest Firefox versions for 1-2 years now in pure LPAC (less privileged appcontainer) successfully.

It’s more secure than default Firefox and significantly faster.

I’ve been working on documenting and streamlining my process and will share the details in the next few days or so.

**Comment by fcharlie** [comment]
> Indeed, multi-process programs are much more complex. Particularly browsers because each process they spawn has a variety of unique sandboxing policies applied to them.
> 
> On a positive note, I have been running latest Firefox versions for 1-2 years now in pure LPAC (less privileged appcontainer) successfully.
> 
> It’s more secure than default Firefox and significantly faster.
> 
> I’ve been working on documenting and streamlining my process and will share the details in the next few days or so.

👍 Great

**Comment by WildByDesign** [comment]
I finally put some time into documenting this and put an initial release out if you guys want to try it.

If you are using my script, it will not mess with your existing Firefox profiles. The script is very specific and also assumes that you have Firefox installed in the default location: C:\Program Files\Mozilla Firefox

EDIT: Forgot to add the link.

Link: https://github.com/WildByDesign/SandboxYourFox
